apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "class-schedule-postgres.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "class-schedule-postgres.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "class-schedule-postgres.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            {{- if .Values.initdb.enabled }}
